input_dir: ../ZAP/Resources
output_dir: ../ZAP/Resources/Generated/

strings:
    inputs: Source/Localization/en.lproj/Localizable.strings
    outputs:
        templateName: structured-swift4
        output: GeneratedStrings.swift

xcassets:
    inputs: Source/Assets.xcassets
    outputs:
        templateName: swift4
        output: ImageAsset.swift
