input_dir: ../ZAP/Resources
output_dir: ../ZAP/Resources/Generated/
strings:
  inputs: Localization/en.lproj/Localizable.strings
  outputs:
    templateName: structured-swift4
    output: GeneratedStrings.swift
